// Built-in exercise library. Loaded into the phone's storage once; after that
// you can edit or delete any of these freely and they will not come back
// (unless you use "Restore built-in exercises").
//
// Each row: name, form cues, movement types, muscle groups, method, role
// role: 1 = main lift (compound, first), 2 = secondary, 3 = isolation / finisher

const SEED_ROWS = [
  // ---------------- CHEST ----------------
  ['Barbell bench press', 'Shoulder blades pinned, slight arch, bar to lower chest, drive feet into the floor.', ['push'], ['chest', 'triceps', 'shoulders'], 'weightlifting', 1],
  ['Incline barbell bench press', 'Bench at 30 degrees, bar to upper chest, elbows about 45 degrees from the torso.', ['push'], ['chest', 'shoulders', 'triceps'], 'weightlifting', 1],
  ['Decline barbell bench press', 'Lock feet in, bar to lower chest, keep wrists stacked over elbows.', ['push'], ['chest', 'triceps'], 'weightlifting', 2],
  ['Dumbbell bench press', 'Kick dumbbells up with the knees, press in a slight arc, stretch at the bottom.', ['push'], ['chest', 'triceps', 'shoulders'], 'weightlifting', 2],
  ['Incline dumbbell press', 'Palms slightly turned in, lower until elbows are just below the bench, press up and in.', ['push'], ['chest', 'shoulders', 'triceps'], 'weightlifting', 2],
  ['Decline dumbbell press', 'Lower dumbbells to the sides of the lower chest, squeeze the chest at the top.', ['push'], ['chest', 'triceps'], 'weightlifting', 2],
  ['Machine chest press', 'Set handles level with the mid chest, press without locking the elbows hard.', ['push'], ['chest', 'triceps'], 'weightlifting', 2],
  ['Smith machine bench press', 'Position the bench so the bar touches the lower chest, control the descent.', ['push'], ['chest', 'triceps', 'shoulders'], 'weightlifting', 2],
  ['Floor press', 'Lie on the floor, lower until the upper arms touch, pause, press without bouncing.', ['push'], ['chest', 'triceps'], 'weightlifting', 2],
  ['Dumbbell fly', 'Slight elbow bend held throughout, lower in a wide arc, hug a barrel to come up.', ['push'], ['chest'], 'weightlifting', 3],
  ['Incline dumbbell fly', 'Bench at 30 degrees, keep the elbow angle fixed, feel the stretch across the upper chest.', ['push'], ['chest'], 'weightlifting', 3],
  ['Cable fly', 'Pulleys at chest height, step forward, bring hands together in front with a slight bend.', ['push'], ['chest'], 'weightlifting', 3],
  ['Low-to-high cable fly', 'Pulleys at the bottom, sweep hands up and in to shoulder height for the upper chest.', ['push'], ['chest', 'shoulders'], 'weightlifting', 3],
  ['High-to-low cable fly', 'Pulleys at the top, sweep hands down and together at the hips for the lower chest.', ['push'], ['chest'], 'weightlifting', 3],
  ['Pec deck', 'Elbows slightly below the shoulders, squeeze the pads together, control the return.', ['push'], ['chest'], 'weightlifting', 3],

  // ---------------- BACK ----------------
  ['Conventional deadlift', 'Bar over mid foot, hips higher than knees, brace, push the floor away, lock out with the glutes.', ['pull', 'legs', 'full-body'], ['back', 'hamstrings', 'glutes'], 'weightlifting', 1],
  ['Sumo deadlift', 'Wide stance, toes out, knees over toes, chest up, drive the knees out as you stand.', ['pull', 'legs', 'full-body'], ['glutes', 'quads', 'hamstrings', 'back'], 'weightlifting', 1],
  ['Trap bar deadlift', 'Stand in the middle of the bar, hips back, push the floor away, stand tall.', ['pull', 'legs', 'full-body'], ['quads', 'glutes', 'hamstrings', 'back'], 'weightlifting', 1],
  ['Rack pull', 'Bar set at knee height, hinge to reach it, drive hips through and squeeze the upper back.', ['pull'], ['back', 'glutes', 'hamstrings'], 'weightlifting', 1],
  ['Barbell bent-over row', 'Hinge to about 45 degrees, pull the bar to the lower ribs, keep the spine neutral.', ['pull'], ['back', 'biceps'], 'weightlifting', 1],
  ['Pendlay row', 'Torso parallel to the floor, bar starts on the floor each rep, explode to the chest.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['T-bar row', 'Chest up, elbows close, pull the handle to the stomach and squeeze the shoulder blades.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['One-arm dumbbell row', 'Hand and knee on the bench, pull the elbow toward the hip, avoid twisting the torso.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Chest-supported dumbbell row', 'Chest on an incline bench, row with the elbows, pause at the top.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Seated cable row', 'Sit tall, pull the handle to the belly, shoulders back, let the arms fully extend.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Machine row', 'Chest against the pad, drive the elbows back, squeeze for a second at the end.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Meadows row', 'Landmine bar, stand side-on, row the end of the bar to the hip with the elbow flared.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Lat pulldown', 'Wide grip, lean back slightly, pull the bar to the upper chest, elbows down and back.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Close-grip lat pulldown', 'Neutral grip handle, pull to the chest, keep the chest tall and squeeze the lats.', ['pull'], ['back', 'biceps'], 'weightlifting', 2],
  ['Straight-arm pulldown', 'Arms nearly straight, sweep the bar down to the thighs using the lats only.', ['pull'], ['back'], 'weightlifting', 3],
  ['Dumbbell pullover', 'Lie across a bench, lower the dumbbell behind the head with a slight elbow bend, pull over.', ['pull'], ['back', 'chest'], 'weightlifting', 3],
  ['Barbell shrug', 'Stand tall, shrug straight up toward the ears, hold, lower slowly. No rolling.', ['pull'], ['back', 'shoulders'], 'weightlifting', 3],
  ['Dumbbell shrug', 'Dumbbells at the sides, shrug up and slightly back, pause at the top.', ['pull'], ['back', 'shoulders'], 'weightlifting', 3],

  // ---------------- SHOULDERS ----------------
  ['Overhead press', 'Bar at the collarbone, brace, press straight up, push the head through at the top.', ['push'], ['shoulders', 'triceps'], 'weightlifting', 1],
  ['Push press', 'Small dip with the knees, drive up with the legs, finish the press with the shoulders.', ['push', 'full-body'], ['shoulders', 'triceps', 'quads'], 'weightlifting', 1],
  ['Seated dumbbell shoulder press', 'Back supported, dumbbells at ear height, press up without clanging them together.', ['push'], ['shoulders', 'triceps'], 'weightlifting', 2],
  ['Arnold press', 'Start palms facing you, rotate out as you press, reverse on the way down.', ['push'], ['shoulders', 'triceps'], 'weightlifting', 2],
  ['Machine shoulder press', 'Seat height so handles start at ear level, press smoothly without locking out.', ['push'], ['shoulders', 'triceps'], 'weightlifting', 2],
  ['Landmine press', 'Half kneeling or standing, press the end of the bar up and forward, brace the core.', ['push'], ['shoulders', 'chest', 'triceps'], 'weightlifting', 2],
  ['Upright row', 'Wide grip, lead with the elbows, pull to the lower chest, keep the bar close.', ['pull'], ['shoulders', 'back'], 'weightlifting', 2],
  ['Dumbbell lateral raise', 'Slight lean forward, raise to shoulder height leading with the elbows, lower slowly.', ['push'], ['shoulders'], 'weightlifting', 3],
  ['Cable lateral raise', 'Cable behind the body, raise the arm out to the side, constant tension throughout.', ['push'], ['shoulders'], 'weightlifting', 3],
  ['Machine lateral raise', 'Pads on the upper arms, raise to shoulder height, control the descent.', ['push'], ['shoulders'], 'weightlifting', 3],
  ['Dumbbell front raise', 'Raise to eye level one arm at a time, no swinging, thumbs slightly up.', ['push'], ['shoulders'], 'weightlifting', 3],
  ['Rear delt fly', 'Hinge forward, arms slightly bent, raise out to the sides, squeeze the rear shoulders.', ['pull'], ['shoulders', 'back'], 'weightlifting', 3],
  ['Reverse pec deck', 'Handles at shoulder height, sweep the arms back, pause, avoid shrugging.', ['pull'], ['shoulders', 'back'], 'weightlifting', 3],
  ['Face pull', 'Rope at face height, pull toward the eyes, elbows high, external rotate at the end.', ['pull'], ['shoulders', 'back'], 'weightlifting', 3],

  // ---------------- BICEPS ----------------
  ['Barbell curl', 'Elbows pinned at the sides, curl without swinging, lower over two to three seconds.', ['pull'], ['biceps'], 'weightlifting', 2],
  ['EZ-bar curl', 'Angled grip is easier on the wrists, keep the elbows still, full range of motion.', ['pull'], ['biceps'], 'weightlifting', 2],
  ['Dumbbell curl', 'Alternate or together, rotate the palm up as you curl, squeeze at the top.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Hammer curl', 'Palms facing each other, curl straight up, hits the outer biceps and forearm.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Incline dumbbell curl', 'Bench at 45 to 60 degrees, arms hang back, curl with a big stretch at the bottom.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Preacher curl', 'Upper arms flat on the pad, do not fully lock out at the bottom, slow negative.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Concentration curl', 'Elbow braced against the inner thigh, curl toward the shoulder, pause at the top.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Cable curl', 'Low pulley, constant tension, keep the elbows in front of the hips.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Bayesian cable curl', 'Face away from the low pulley, arm behind the body, curl with a deep stretch.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Spider curl', 'Chest on an incline bench, arms hang straight down, curl up and squeeze hard.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Reverse curl', 'Palms down, curl the bar, targets the forearms and outer biceps.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Zottman curl', 'Curl palms up, rotate to palms down at the top, lower slowly.', ['pull'], ['biceps'], 'weightlifting', 3],
  ['Machine bicep curl', 'Upper arms on the pad, curl through the full range, control the return.', ['pull'], ['biceps'], 'weightlifting', 3],

  // ---------------- TRICEPS ----------------
  ['Close-grip bench press', 'Hands shoulder width, elbows tucked, bar to the lower chest, press up.', ['push'], ['triceps', 'chest'], 'weightlifting', 2],
  ['JM press', 'Hybrid of close-grip press and skull crusher, lower the bar toward the chin, elbows forward.', ['push'], ['triceps'], 'weightlifting', 2],
  ['Skull crusher', 'EZ-bar, lower to the forehead or just behind, elbows pointing up, extend.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Overhead dumbbell triceps extension', 'One dumbbell with both hands, elbows close to the head, lower behind the neck.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Cable overhead triceps extension', 'Rope from a low pulley, face away, extend overhead with a full stretch.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Rope triceps pushdown', 'Elbows pinned, push down and split the rope at the bottom, control the way up.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Straight-bar triceps pushdown', 'Elbows at the sides, press to full lockout, do not let the elbows drift forward.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Single-arm cable pushdown', 'Underhand or overhand, one arm at a time, full lockout each rep.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Dumbbell kickback', 'Hinge forward, upper arm parallel to the floor, extend the elbow fully, squeeze.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Tate press', 'Lie on a bench, dumbbells over the chest, lower them inward to the chest with elbows out.', ['push'], ['triceps'], 'weightlifting', 3],
  ['Machine triceps extension', 'Elbows on the pad, extend fully, slow return.', ['push'], ['triceps'], 'weightlifting', 3],

  // ---------------- QUADS ----------------
  ['Barbell back squat', 'Brace hard, sit down and back, knees track over toes, drive up through the whole foot.', ['legs'], ['quads', 'glutes', 'hamstrings'], 'weightlifting', 1],
  ['Front squat', 'Bar on the front shoulders, elbows high, stay upright, sit straight down.', ['legs'], ['quads', 'glutes'], 'weightlifting', 1],
  ['Safety bar squat', 'Handles in front, stay tall against the forward pull, squat to depth.', ['legs'], ['quads', 'glutes'], 'weightlifting', 1],
  ['Box squat', 'Sit back onto the box, pause without relaxing, drive up explosively.', ['legs'], ['quads', 'glutes', 'hamstrings'], 'weightlifting', 1],
  ['Hack squat', 'Feet mid platform, lower until thighs pass parallel, push through the whole foot.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Leg press', 'Feet shoulder width, lower until the hips start to tuck, do not lock the knees.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Pendulum squat', 'Stay upright against the pad, deep range, push through the heels.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Smith machine squat', 'Feet slightly forward of the bar, squat straight down, knees forward.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Zercher squat', 'Bar in the crook of the elbows, stay upright, squat between the knees.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Goblet squat', 'Hold a dumbbell at the chest, elbows inside the knees at the bottom, chest up.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Bulgarian split squat', 'Rear foot on a bench, drop straight down, front knee tracks over the toes.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Walking lunge', 'Long steps, back knee to just above the floor, push off the front heel.', ['legs'], ['quads', 'glutes', 'hamstrings'], 'weightlifting', 2],
  ['Reverse lunge', 'Step back, lower the back knee, drive up through the front foot. Kinder on the knees.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Step-up', 'Box at knee height, drive through the top foot only, control the step down.', ['legs'], ['quads', 'glutes'], 'weightlifting', 2],
  ['Leg extension', 'Pad on the lower shins, extend fully, squeeze the quads, lower slowly.', ['legs'], ['quads'], 'weightlifting', 3],
  ['Sissy squat', 'Hold a support, lean back and bend the knees forward, heels up, deep quad stretch.', ['legs'], ['quads'], 'weightlifting', 3],

  // ---------------- HAMSTRINGS ----------------
  ['Romanian deadlift', 'Soft knees, push the hips back, bar slides down the thighs, stop when the hamstrings pull.', ['legs', 'pull'], ['hamstrings', 'glutes', 'back'], 'weightlifting', 1],
  ['Stiff-leg deadlift', 'Legs nearly straight, hinge from the hips, bar to mid shin, feel the stretch.', ['legs', 'pull'], ['hamstrings', 'glutes', 'back'], 'weightlifting', 1],
  ['Dumbbell Romanian deadlift', 'Dumbbells close to the legs, hips back, flat back, squeeze the glutes to stand.', ['legs'], ['hamstrings', 'glutes'], 'weightlifting', 2],
  ['Single-leg Romanian deadlift', 'One leg, hinge forward with the free leg extending back, hips square.', ['legs'], ['hamstrings', 'glutes'], 'weightlifting', 2],
  ['Good morning', 'Bar on the back, soft knees, hinge until the torso is near parallel, stand tall.', ['legs'], ['hamstrings', 'glutes', 'back'], 'weightlifting', 2],
  ['Glute-ham raise', 'Knees on the pad, lower the torso slowly, pull back up with the hamstrings.', ['legs'], ['hamstrings', 'glutes'], 'weightlifting', 2],
  ['Lying leg curl', 'Hips pressed into the pad, curl to the glutes, lower over three seconds.', ['legs'], ['hamstrings'], 'weightlifting', 3],
  ['Seated leg curl', 'Thigh pad tight, curl fully under the seat, control the return.', ['legs'], ['hamstrings'], 'weightlifting', 3],
  ['Standing single-leg curl', 'One leg at a time, curl to the glute, squeeze, slow negative.', ['legs'], ['hamstrings'], 'weightlifting', 3],
  ['45-degree back extension', 'Hips on the pad, hinge down, come up to neutral, squeeze glutes and hamstrings.', ['legs'], ['hamstrings', 'glutes', 'back'], 'weightlifting', 3],

  // ---------------- GLUTES ----------------
  ['Barbell hip thrust', 'Upper back on a bench, bar over the hips, drive up to a flat line, chin tucked.', ['legs'], ['glutes', 'hamstrings'], 'weightlifting', 1],
  ['Machine hip thrust', 'Set the pad on the hips, drive up and squeeze for a full second at the top.', ['legs'], ['glutes', 'hamstrings'], 'weightlifting', 2],
  ['Barbell glute bridge', 'On the floor, bar over the hips, push through the heels, squeeze at the top.', ['legs'], ['glutes', 'hamstrings'], 'weightlifting', 2],
  ['Kettlebell swing', 'Hinge, not squat. Snap the hips forward, bell floats to chest height.', ['legs', 'full-body'], ['glutes', 'hamstrings', 'back'], 'weightlifting', 2],
  ['Curtsy lunge', 'Step back and across behind the front leg, lower, drive up through the front foot.', ['legs'], ['glutes', 'quads'], 'weightlifting', 2],
  ['Cable pull-through', 'Face away from a low pulley, rope between the legs, hinge and snap the hips forward.', ['legs'], ['glutes', 'hamstrings'], 'weightlifting', 3],
  ['Cable glute kickback', 'Ankle strap, hinge slightly, kick back and up, squeeze, control the return.', ['legs'], ['glutes'], 'weightlifting', 3],
  ['Hip abduction machine', 'Sit tall or lean forward, push the knees out, pause, resist the return.', ['legs'], ['glutes'], 'weightlifting', 3],
  ['Reverse hyperextension', 'Hips on the pad, swing the legs up behind using the glutes, no back arching.', ['legs'], ['glutes', 'hamstrings'], 'weightlifting', 3],
  ['Frog pump', 'Soles of the feet together, knees out, pump the hips up, high reps.', ['legs'], ['glutes'], 'weightlifting', 3],
  ['Farmer\'s carry', 'Heavy dumbbells at the sides, walk tall with short quick steps, brace throughout.', ['full-body', 'core'], ['abs', 'back', 'shoulders'], 'weightlifting', 2],

  // ---------------- CALVES ----------------
  ['Standing calf raise', 'Full stretch at the bottom, pause, rise onto the toes, hold at the top.', ['legs'], ['calves'], 'weightlifting', 3],
  ['Seated calf raise', 'Pad on the lower thighs, deep stretch, rise fully, hits the lower calf.', ['legs'], ['calves'], 'weightlifting', 3],
  ['Leg press calf raise', 'Toes on the bottom edge of the platform, push through the balls of the feet.', ['legs'], ['calves'], 'weightlifting', 3],
  ['Donkey calf raise', 'Hinged forward with the hips supported, full stretch and full contraction.', ['legs'], ['calves'], 'weightlifting', 3],
  ['Single-leg dumbbell calf raise', 'One foot on a step, dumbbell in the same-side hand, slow and full range.', ['legs'], ['calves'], 'weightlifting', 3],
  ['Smith machine calf raise', 'Balls of the feet on a block, bar on the back, rise and pause at the top.', ['legs'], ['calves'], 'weightlifting', 3],

  // ---------------- ABS (weighted) ----------------
  ['Cable crunch', 'Kneel facing the pulley, rope by the head, crunch the ribs toward the hips.', ['core'], ['abs'], 'weightlifting', 3],
  ['Machine crunch', 'Handles or pad set high, curl the torso down, pause, slow return.', ['core'], ['abs'], 'weightlifting', 3],
  ['Weighted decline sit-up', 'Plate on the chest, lower slowly, come up without yanking the neck.', ['core'], ['abs'], 'weightlifting', 3],
  ['Weighted plank', 'Plate on the upper back, straight line from head to heels, breathe.', ['core'], ['abs'], 'weightlifting', 3],
  ['Pallof press', 'Cable at chest height, side-on, press straight out and resist the twist.', ['core'], ['abs'], 'weightlifting', 3],
  ['Cable woodchop', 'High to low across the body, rotate from the hips and ribs, arms stay long.', ['core'], ['abs'], 'weightlifting', 3],
  ['Landmine rotation', 'Hold the end of the bar with straight arms, sweep it side to side, pivot the feet.', ['core'], ['abs'], 'weightlifting', 3],
  ['Dumbbell side bend', 'One dumbbell, bend sideways and return, do not lean forward.', ['core'], ['abs'], 'weightlifting', 3],
  ['Weighted Russian twist', 'Lean back, feet up or down, rotate the plate side to side with control.', ['core'], ['abs'], 'weightlifting', 3],

  // ---------------- CALISTHENICS ----------------
  ['Pull-up', 'Full hang, pull the chest to the bar, control the descent. Overhand grip.', ['pull'], ['back', 'biceps'], 'calisthenics', 1],
  ['Chin-up', 'Underhand grip, chin over the bar, more biceps than the pull-up.', ['pull'], ['back', 'biceps'], 'calisthenics', 1],
  ['Inverted row', 'Bar at hip height, body straight, pull the chest to the bar. Feet up to make it harder.', ['pull'], ['back', 'biceps'], 'calisthenics', 2],
  ['Dead hang', 'Hang from the bar with straight arms, shoulders active, build grip and lat stretch.', ['pull'], ['back'], 'calisthenics', 3],
  ['Push-up', 'Hands under the shoulders, body straight, chest to the floor, elbows about 45 degrees.', ['push'], ['chest', 'triceps', 'shoulders'], 'calisthenics', 2],
  ['Diamond push-up', 'Hands together under the chest, elbows tucked, heavy on the triceps.', ['push'], ['triceps', 'chest'], 'calisthenics', 3],
  ['Pike push-up', 'Hips high in a pike, lower the head toward the floor, press back up. Shoulder focus.', ['push'], ['shoulders', 'triceps'], 'calisthenics', 2],
  ['Handstand push-up', 'Against a wall, lower the head to the floor or a pad, press back to lockout.', ['push'], ['shoulders', 'triceps'], 'calisthenics', 1],
  ['Dip', 'Lean forward for chest, upright for triceps, lower until the upper arms are parallel.', ['push'], ['chest', 'triceps', 'shoulders'], 'calisthenics', 1],
  ['Bench dip', 'Hands on a bench behind you, lower until elbows reach 90 degrees, press up.', ['push'], ['triceps'], 'calisthenics', 3],
  ['Bodyweight squat', 'Feet shoulder width, sit down between the heels, chest up, full depth.', ['legs'], ['quads', 'glutes'], 'calisthenics', 2],
  ['Pistol squat', 'One leg, other leg straight in front, sit all the way down and stand up.', ['legs'], ['quads', 'glutes'], 'calisthenics', 1],
  ['Bodyweight lunge', 'Step forward, back knee to just above the floor, push back to standing.', ['legs'], ['quads', 'glutes'], 'calisthenics', 2],
  ['Nordic hamstring curl', 'Ankles anchored, lower the body forward as slowly as possible, push back up.', ['legs'], ['hamstrings'], 'calisthenics', 2],
  ['Bodyweight glute bridge', 'On the back, feet flat, drive the hips up, squeeze the glutes at the top.', ['legs'], ['glutes', 'hamstrings'], 'calisthenics', 3],
  ['Single-leg glute bridge', 'One foot down, other leg extended, drive up without letting the hips tilt.', ['legs'], ['glutes', 'hamstrings'], 'calisthenics', 3],
  ['Hanging leg raise', 'Hang from the bar, raise straight legs to horizontal or higher, no swinging.', ['core'], ['abs'], 'calisthenics', 2],
  ['Hanging knee raise', 'Hang, bring the knees up toward the chest, curl the pelvis at the top.', ['core'], ['abs'], 'calisthenics', 3],
  ['Ab wheel rollout', 'Kneel, roll out as far as you can keep the back flat, pull back with the abs.', ['core'], ['abs'], 'calisthenics', 2],
  ['Plank', 'Forearms down, body in a straight line, squeeze the glutes, breathe.', ['core'], ['abs'], 'calisthenics', 3],
  ['Side plank', 'On one forearm, hips stacked and lifted, hold, then switch sides.', ['core'], ['abs'], 'calisthenics', 3],
  ['Hollow body hold', 'On the back, lower back pressed down, arms and legs hovering, hold.', ['core'], ['abs'], 'calisthenics', 3],
  ['Dead bug', 'On the back, arms up, lower opposite arm and leg while the lower back stays flat.', ['core'], ['abs'], 'calisthenics', 3],
  ['Mountain climber', 'Push-up position, drive the knees in alternately at pace, hips level.', ['core', 'full-body'], ['abs', 'quads'], 'calisthenics', 3],
  ['Burpee', 'Drop to a push-up, jump the feet in, jump up. Keep a steady rhythm.', ['full-body'], ['quads', 'chest', 'abs'], 'calisthenics', 2],
  ['Superman', 'Lie face down, lift arms and legs together, hold briefly, lower.', ['core'], ['back', 'glutes'], 'calisthenics', 3],

  // ---------------- CARDIO ----------------
  ['Treadmill run', 'Steady pace you could hold a short sentence at, or intervals of hard and easy.', ['full-body'], ['quads', 'hamstrings', 'calves'], 'cardio', 2],
  ['Incline treadmill walk', 'Set the incline high, walk briskly without holding the rails.', ['legs'], ['glutes', 'calves', 'hamstrings'], 'cardio', 3],
  ['Rowing machine', 'Legs, then body, then arms. Reverse on the way back. Drive with the legs.', ['full-body', 'pull'], ['back', 'quads', 'glutes'], 'cardio', 2],
  ['Stationary bike', 'Seat at hip height, steady spin or intervals, keep the upper body relaxed.', ['legs'], ['quads', 'glutes'], 'cardio', 3],
  ['Assault bike', 'Push and pull with the arms while pedalling, brutal for intervals.', ['full-body'], ['quads', 'shoulders', 'back'], 'cardio', 2],
  ['Stair climber', 'Full steps, light hands on the rails, upright posture.', ['legs'], ['glutes', 'quads', 'calves'], 'cardio', 3],
  ['Jump rope', 'Small hops on the balls of the feet, wrists turn the rope, relaxed shoulders.', ['full-body'], ['calves'], 'cardio', 3],
  ['Sled push', 'Arms locked, lean in, drive with short powerful steps.', ['legs', 'full-body'], ['quads', 'glutes', 'calves'], 'cardio', 2],
  ['Elliptical', 'Low impact, push and pull the handles, keep the heels down.', ['full-body'], ['quads', 'glutes'], 'cardio', 3],

  // ---------------- MOBILITY ----------------
  ['Cat-cow', 'On all fours, arch and round the spine slowly, one breath per position.', ['core'], ['back', 'abs'], 'mobility', 3],
  ['World\'s greatest stretch', 'Lunge, hand inside the front foot, rotate and reach up, then hamstring rock back.', ['full-body'], ['hamstrings', 'glutes', 'back'], 'mobility', 3],
  ['90/90 hip switch', 'Sit with both knees at 90 degrees, rotate the knees side to side, stay tall.', ['legs'], ['glutes'], 'mobility', 3],
  ['Couch stretch', 'Rear knee against a wall, front foot forward, squeeze the glute, stay upright.', ['legs'], ['quads'], 'mobility', 3],
  ['Kneeling hip flexor stretch', 'Half kneeling, tuck the pelvis, shift forward gently, feel the front of the hip.', ['legs'], ['quads', 'glutes'], 'mobility', 3],
  ['Pigeon stretch', 'Front shin across the body, back leg straight, fold forward over the front leg.', ['legs'], ['glutes'], 'mobility', 3],
  ['Deep squat hold', 'Sit in the bottom of a squat, elbows push the knees out, heels down.', ['legs'], ['quads', 'glutes', 'calves'], 'mobility', 3],
  ['Ankle dorsiflexion rock', 'Half kneeling, drive the front knee over the toes, heel stays down.', ['legs'], ['calves'], 'mobility', 3],
  ['Standing hamstring stretch', 'Heel on a low box, hinge forward with a flat back until the hamstring pulls.', ['legs'], ['hamstrings'], 'mobility', 3],
  ['Thoracic rotation', 'On all fours, hand behind the head, rotate the elbow up toward the ceiling.', ['pull'], ['back'], 'mobility', 3],
  ['Band shoulder dislocates', 'Wide grip on a band, take it over the head and behind, arms straight.', ['push'], ['shoulders', 'chest'], 'mobility', 3],
  ['Wall slides', 'Back and arms against a wall, slide the arms up and down keeping contact.', ['push'], ['shoulders', 'back'], 'mobility', 3],
  ['Doorway chest stretch', 'Forearm on the door frame, step through gently, feel the chest open.', ['push'], ['chest', 'shoulders'], 'mobility', 3],
];

// Turn a row into a full exercise record with stable ids.
function seedExercises() {
  return SEED_ROWS.map(([name, description, movement, muscles, method, priority]) => ({
    id: 'seed:' + slug(name),
    name,
    description,
    notes: '',
    movementTypes: movement.map(m => 'movement:' + m),
    muscleGroups: muscles.map(m => 'muscle:' + m),
    methods: ['method:' + method],
    priority,
    builtIn: true,
    createdAt: 0,
    updatedAt: 0,
  }));
}
